[package]
name = "wonderswan-rust"
version = "0.1.0"
authors = ["Oriol Burgaya <oriolbv@gmail.com>"]
edition = "2018"

[dependencies]
orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop" }